### ISSUE TITLE
CI provider Shippable no longer operating

### ISSUE THREAD

**Issue by MikeMcC399** [watson/ci-info#117]
[README > Supported CI tools](https://github.com/watson/ci-info/blob/master/README.md#supported-ci-tools) lists Shippable under "Officially supported CI servers":

| Name                                    | Constant       | isPR |
| --------------------------------------- | -------------- | ---- |
| [Shippable](https://www.shippable.com/) | `ci.SHIPPABLE` | ✅    |

It appears that Shippable no longer operates as a CI provider.

**Details:**

- Ci name: Shippable
- Website: https://www.shippable.com/

## Other details

- The website https://www.shippable.com/ domain is unknown and the previously operating websites https://app.shippable.com/ and http://docs.shippable.com/ are no longer reachable.
- Shippable's GitHub repositories under https://github.com/Shippable have not been updated since September 16, 2021.

- See [We’ve Acquired Shippable to Complete DevOps Pipeline Automation From Code to Production](https://jfrog.com/blog/weve-acquired-shippable-to-complete-devops-pipeline-automation-from-code-to-production/) February 21, 2019. JFrog stated they would replace shippable with [JFrog Pipelines](https://www.jfrog.com/confluence/display/JFROG/JFrog+Pipelines).

**Comment by sibiraj-s** [comment]
Removed in v4.0.0
