### ISSUE TITLE
Possibility of a static identifier? 

### ISSUE THREAD

**Issue by trek** [watson/ci-info#130]
We'd like to store which CI system a customer is using in a metrics system for reporting and noticed that `ci.name` values are not guaranteed to remain the same. Would it be useful to have `ci.identifer` or something like it to solve for this use case?

We briefly looked at mapping `ci.<VENDOR-CONSTANT>` against the constant name but this seems to require that we keep a list of values which we'd prefer not to do.

**Comment by sibiraj-s** [comment]
This is published in [v4.1.0](https://github.com/watson/ci-info/releases/tag/v4.1.0), now you could to `ci.id` to get the constant name
