### ISSUE TITLE
Add Concourse to the list of detected servers

### ISSUE THREAD

**Issue by cah-briangantzler** [watson/ci-info#20]
**Details:**
 - Ci name: Concourse
 - Website: https://concourse-ci.org/
 - Default env variables: Unknown

**Environment variables**

<details>
<summary>Environment variables example</summary> 

```
// Add a list of actual environment variables available to the build here
// Please keep the blank line above and below the code block
// WARNING: Be careful not to include any private or otherwise sensitive information
```

</details>

**Additional context**
Concourse runs a series of steps each in its own docker container. Environment variables are 
passed into each container. The ones I work with are the ones I passed unique to my job and environment. I have not yet had to deal with any global environment variables that would identify it as Concourse, although Im sure there must be some.

**Comment by Sibiraj-S** [comment]
Hi, @cah-briangantzler. Concosure doesn't expose any environment variables to detect their platform.  Refer https://github.com/concourse/concourse/issues/2105#issuecomment-375338690

There is an existing Feature Request to detect concosure here https://github.com/watson/is-ci/issues/13

**Comment by cah-briangantzler** [comment]
Thanks for the response, I did do a cursory check for issues, and didnt see this one.

Even though it runs in containers and I can set environment variables, would have thought that At lease a couple were available.

Thanks for the attention.
