### ISSUE TITLE
Support for Gitlab

### ISSUE THREAD

**Issue by PolGuixe** [watson/ci-info#32]
**Details:**
 - Ci name: Gitlab
 - Website: https://gitlab.com
 - Default env variables: https://docs.gitlab.com/ee/ci/variables/#predefined-environment-variables

**Environment variables**

See link above

**Additional context**
None

**Comment by sibiraj-s** [comment]
@PolGuixe Gitlab is already supported. any bugs?

**Comment by PolGuixe** [comment]
I opened it a long time ago. 

I haven't tried it since yet. If I observe any bugs I'll let you know.
