### ISSUE TITLE
Detect PR for AWS CodeBuild

### ISSUE THREAD

**Issue by charsleysa** [watson/ci-info#38]
AWS CodeBuild now has an environment variable that works with GitHub and BitBucket when setup using WebHooks which can be used to detect PR builds.

`CODEBUILD_WEBHOOK_EVENT` with values `PULL_REQUEST_CREATED`, `PULL_REQUEST_UPDATED`, and `PULL_REQUEST_REOPENED`

**Comment by sibiraj-s** [comment]
This is now published in v4.1.0.
