### ISSUE TITLE
Conflicts with nestor

### ISSUE THREAD

**Issue by thisgeek** [watson/ci-info#4]
The vendor detection conflicts with one of the [configuration options of nestor](https://www.npmjs.com/package/nestor#configuration). See cliffano/nestor#49. With the `JENKINS_URL` configured for nestor, ci-info will consider my dev machine a CI server.

Not sure where we should say the fault lies, but I want to at least register this as a possible issue for some people.

**Comment by watson** [comment]
@thisgeek We could solve this by adding an extra check to see if for instance `BUILD_ID` is set as well. So it's not only `JENKINS_URL` that determines this. Would that work for you?

**Comment by thisgeek** [comment]
Yes I think it would.

**Comment by watson** [comment]
Fixed and released in version 1.1.2
