### ISSUE TITLE
Maintenance: Do you need help maintaining this project?

### ISSUE THREAD

**Issue by fearphage** [watson/ci-info#44]
There are several issues that have been open and idle for months. Do you need help maintaining the project? 

I'd like to volunteer my services of reviewing and merging PRs among other things. I'm sure there are others in the community that would be willing to share the load as well.

**Comment by JounQin** [comment]
@watson Can you care about this issue to fix issues like #31, #38 and #41, etc.

**Comment by sibiraj-s** [comment]
Thanks @fearphage. I just got publish permissions today. I have published v3.0.0 just now. All Contributions are welcomed 🙏 

@JounQin I have already fixed #31 and #41. couldn't find proper environment variables for AWS. I will see if I could do something this week. meanwhile PR's are welcome.
