### ISSUE TITLE
exported isCI ignores env variable set to false

### ISSUE THREAD

**Issue by polmabri** [watson/ci-info#50]
In the official docker image node:14-buster the env variable CI is set to true:

`
CI=true
`

I use this container for developing purposes (as base of a vscode devcontainer) and in order to install husky it was necessary to set the env variable CI to false:

`
CI=false
`

Unfortunately isCI returns true in this case, because env.CI has the value "false" (string) and the current used implementation converts this value to true:

```js
// returns true
!!("false")
```

```js
exports.isCI = !!(
  env.CI || // Travis CI, CircleCI, Cirrus CI, Gitlab CI, Appveyor, CodeShip, dsari
  env.CONTINUOUS_INTEGRATION || // Travis CI, Cirrus CI
  env.BUILD_NUMBER || // Jenkins, TeamCity
  env.RUN_ID || // TaskCluster, dsari
  exports.name ||
  false
)
```

**Comment by Knagis** [comment]
`env.CI="false"` should also bypass the other checks made here, so that it can be used to get non-CI mode on Jenkins etc.
