### ISSUE TITLE
Add LayerCI

### ISSUE THREAD

**Issue by emanuelb** [watson/ci-info#63]
- Ci name: LayerCI
 - Website: https://layerci.com/

From:
https://layerci.com/docs/layerfile-reference/intro#build-env
https://github.com/layer-devops/docs/blob/4e0b0070b15bda6b3001dff0cc87f122009d51e0/layerfile-reference/build-env.md#build-env

Looks like the below is related env vars:

`CI=true`, `IS_CI_MACHINE=true`, `CI_MACHINE=true`, `IN_CI_MACHINE=true`, `IN_CI=true`

These `CI` variables are always `true` in LayerCI.

`LAYERCI=true`

`LAYERCI` is always `true` in LayerCI test runs.

**Comment by sibiraj-s** [comment]
> LAYERCI is always true in LayerCI test runs.

Can you clarify this if possible? is test run a different kind of run?

**Comment by emanuelb** [comment]
> Can you clarify this if possible? is test run a different kind of run?

I can't, don't have account/used it, and don't know the answer to this question, just saw this useful library used elsewhere (CI detection needed to avoid known bugs) and decided to contribute by looking for missing support of CIs (will open more issues shortly)

**Comment by sibiraj-s** [comment]
It would be great if you can open issue for CI with clear documentation or a familiar CI/CD. Issues like this will be difficult to fix.

**Comment by emanuelb** [comment]
well, someone else who know better may see the issues and help :) do my best to find related info and post it in the issue.
regarding this issue & LayerCI, maybe open issue in their docs repo https://github.com/layer-devops/docs/ to ask about the `LAYERCI` env? and say that such env is always useful for detection of specific CI...

**Comment by sibiraj-s** [comment]
> maybe open issue in their docs repo https://github.com/layer-devops/docs/ to ask about the LAYERCI env? and say that such env is always useful for detection of specific CI...

Yeah you can do that.

**Comment by emanuelb** [comment]
> Yeah you can do that.

Done, opened issue: https://github.com/layer-devops/docs/issues/29
