### ISSUE TITLE
Add Codefresh

### ISSUE THREAD

**Issue by emanuelb** [watson/ci-info#64]
- Ci name: Codefresh
 - Website: https://codefresh.io/

env variables:
https://codefresh.io/docs/docs/codefresh-yaml/variables/
same page on github: https://github.com/codefresh-io/docs.codefresh.io/blob/master/_docs/codefresh-yaml/variables.md

looks like only `CI=true`, there are some env vars starting with `CF_`

**Comment by sibiraj-s** [comment]
Yeah. Looks like we can use `CF_BUILD_ID` and `CF_PULL_REQUEST_NUMBER`

**Comment by sibiraj-s** [comment]
Done.
