### ISSUE TITLE
Visual Studio Team Services not working

### ISSUE THREAD

**Issue by fa10** [watson/ci-info#7]
Hi,

It does not work with VSTS Builds.
Anyone that has encountered the same?

**Comment by watson** [comment]
I would have thought that this was covered by the Team Foundation Server check 🤔

I found [this page](https://docs.microsoft.com/en-us/vsts/pipelines/build/variables?view=vsts) describing the predefined build variables and it lists `TF_BUILD` as one of them, which we already check for.

I don't have access to a Team Services instance my self, so i can't verify any of this. Can someone maybe comment with a list of the environment variables that are present on their Visual Studio Team Services?

**Comment by watson** [comment]
Support for Azure Pipelines was just added in #23. This should cover Visual Studio Team Services as well. It will be included in the next version of ci-info which we'll release shortly. I'll close this issue for now.
