### ISSUE TITLE
Please add Woodpecker CI

### ISSUE THREAD

**Issue by kaeedo** [watson/ci-info#72]
**Details:**
 - Ci name: Woodpecker CI
 - Website: [[e.g. https://travis-ci.com/]](https://woodpecker-ci.org/)
 - Default env variables: https://woodpecker-ci.org/docs/usage/environment#built-in-environment-variables

**Additional context**
Woodpecker is a community fork of Drone CI. 

Thank you

**Comment by 6543** [comment]
-> #90
