### ISSUE TITLE
Add Releasehub?

### ISSUE THREAD

**Issue by apenney** [watson/ci-info#74]
Hi,

We have a customer who uses is-ci to tweak their behavior when building, and they've noticed that we're not supported (which is not a surprise, we're a small SaaS company).  I had a look at your code and it looks like you just check for env vars, is there any chance you could add a check for:

* RELEASE_COMMIT_SHA 

I know we have kind of a generic name, but I think this should be a pretty unique identifier.

**Comment by sibiraj-s** [comment]
Fixed in v3.7.0
