### ISSUE TITLE
EAS variable is not exposed

### ISSUE THREAD

**Issue by bdellegrazie** [watson/ci-info#75]
**Details:**
 - Ci name: expo application services (EAS)
 - Website: https://expo.dev

**Additional context**
The EAS variable (`ci.EAS`) does not appear to be visible at all (not exported) as a constant.

**Comment by sibiraj-s** [comment]
Its `ci.EAS_BUILD`

**Comment by bdellegrazie** [comment]
Still not exported, regardless

**Comment by sibiraj-s** [comment]
Fix for typings is published in v3.3.1.

**Comment by bdellegrazie** [comment]
Thank you!
