### ISSUE TITLE
Consider another heuristics USER=tester?

### ISSUE THREAD

**Issue by stefanpenner** [watson/ci-info#8]
Some companies, have a  more bespoke CI setup, is there any interest in also adding the check:

```
require('username').sync() === 'tester'
```

**Comment by watson** [comment]
Interesting heuristic. I wonder how common the `tester` user is. If we used that for detecting CI, we wouldn't be able to say much about it though. But I guess we could have catch all name like `unknown` or something.

Do you know how common using a this username is?

**Comment by stefanpenner** [comment]
I’m not sure how common it is. But I can Only speak to the company I work for using this for its bespoke CI system.

I’m not sure how reliable the above is, I wouldn’t want to push this and introduce a large number of false positives.

**Comment by watson** [comment]
Do you mind if I leave this issue open for a while longer to see if anybody else have any input? I'm currently leaning towards not supporting something like this though. But let's see if others have any input 😃

**Comment by stefanpenner** [comment]
@watson sounds good to me.

**Comment by watson** [comment]
I'll close this issue for now. Feel free to leave a comment if there's anything new 😃
