### ISSUE TITLE
Add Earthly

### ISSUE THREAD

**Issue by emanuelb** [watson/ci-info#88]
**Details:**

- Ci name: Earthly
- Website: https://earthly.dev/
- Default env variables: 

when `--ci` is used it's like `EARTHLY_CI=true` env var
https://github.com/earthly/earthly/blob/86470db35c11376416c0575f6ac30ca2b0e04543/docs/earthly-command/earthly-command.md#--ci
https://github.com/earthly/earthly/blob/7189a1547f06ddb1ff676e17acfa81135548ad9f/cmd/earthly/flags.go#L170-L175

**Comment by sibiraj-s** [comment]
Added in v4.0.0
