### ISSUE TITLE
Remove Solano CI

### ISSUE THREAD

**Issue by OneCricketeer** [watson/ci-info#99]
This does not appear to be a CI platform anymore.

Crunchbase reposts as closed: https://www.crunchbase.com/organization/solano-labs

Twitter inactive since 2017

<img width="703" alt="image" src="https://user-images.githubusercontent.com/1930631/203171747-a636b917-eb45-424b-8dfa-7fe4ca23e6e0.png">

**Comment by sibiraj-s** [comment]
Thanks @OneCricketeer . It is a breaking change. Let's keep this issue open for some time before removing it. See if anyone has comments on this.

**Comment by sibiraj-s** [comment]
Removed in v4.0.0
